#!/usr/bin/env bash
# Create a new git worktree with its own .env (unique ports).
# Usage: scripts/new-worktree.sh <branch-name>
# Example: scripts/new-worktree.sh feature/filters

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BRANCH="${1:?Usage: $0 <branch-name>}"

# Worktrees live in /tmp for easy cleanup (cleared on reboot)
WORKTREE_DIR="/tmp/demo_mentorcruise_webinar/${BRANCH//\//-}"

# ── Port allocation ───────────────────────────────────────────────────────────
# Reserved slots (edit here to add explicit assignments):
declare -A RESERVED=(
  ["main"]="3001 5173"
  ["feature/filters"]="3002 5174"
  ["feature/due-dates"]="3003 5175"
  ["feature/priority"]="3004 5176"
)

if [ -n "${RESERVED[$BRANCH]}" ]; then
  BACKEND_PORT=$(echo "${RESERVED[$BRANCH]}" | awk '{print $1}')
  FRONTEND_PORT=$(echo "${RESERVED[$BRANCH]}" | awk '{print $2}')
else
  # Auto-derive from branch hash to avoid collisions (range 3100-3199 / 5200-5299)
  HASH=$(echo -n "$BRANCH" | cksum | awk '{print $1 % 100}')
  BACKEND_PORT=$((3100 + HASH))
  FRONTEND_PORT=$((5200 + HASH))
fi
# ─────────────────────────────────────────────────────────────────────────────

# Create the git worktree + branch
git -C "$ROOT" worktree add -b "$BRANCH" "$WORKTREE_DIR"

# Write .env into the worktree root — both backend and frontend read this
cat > "$WORKTREE_DIR/.env" <<EOF
# Ports for this worktree (branch: ${BRANCH})
# Generated by scripts/new-worktree.sh — do not commit
PORT=${BACKEND_PORT}
VITE_PORT=${FRONTEND_PORT}
VITE_API_URL=http://localhost:${BACKEND_PORT}
EOF

echo "[new-worktree] .env written to $WORKTREE_DIR/.env"

# Install deps (node_modules are not shared across worktrees)
echo "[new-worktree] installing backend deps..."
cd "$WORKTREE_DIR/backend" && npm install --silent

echo "[new-worktree] installing frontend deps..."
cd "$WORKTREE_DIR/frontend" && npm install --silent

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Worktree ready"
echo "  branch:   $BRANCH"
echo "  path:     $WORKTREE_DIR"
echo "  backend:  http://localhost:${BACKEND_PORT}"
echo "  frontend: http://localhost:${FRONTEND_PORT}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd $WORKTREE_DIR"
echo "  scripts/start-with-log.sh all"
echo ""
